import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from './Component/Header'
import Footer from './Component/Footer'
import { SessionProvider } from "next-auth/react"
import Provider from './Component/Provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr">
      <body className={inter.className}>
        <Provider>
          <Header />
            {children}
          <Footer />
        </Provider>
      </body>
    </html>
  )
}
